# Generated by Django 5.2.1 on 2025-05-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('rejected', 'Принята'), ('accepted', 'Отклонена'), ('pending', 'Ожидает')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_receiver', to='ads.ad')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_sender', to='ads.ad')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ad_sender', 'ad_receiver'), name='Exchange constraint')],
            },
        ),
    ]
