# Generated by Django 5.2.1 on 2025-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_exchangeproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принята'), ('rejected', 'Отклонена'), ('pending', 'Ожидает')], default='pending', max_length=32),
        ),
    ]
